backend:
  name: git-gateway
  # name: test-repo #local testing
  branch: development # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - label: 'Hero Banner'
          name: 'hero_banner'
          widget: 'object'
          fields:
            - { label: 'Image', name: 'image', widget: image, required: false }
            - label: 'text'
              name: 'text'
              widget: 'object'
              fields:
                - { label: 'Headline', name: 'headline', widget: 'text', required: false }
                - { label: 'Subtext', name: 'subtext', widget: 'text', required: false }
            - label: 'Background Size'
              name: 'background_size'
              widget: 'select'
              required: false
              options: 
                - { label: 'Cover', value: 'cover' }
                - { label: 'Contain', value: 'contain' }
            - label: 'Backdrop'
              name: 'backdrop'
              widget: 'object'
              fields:
                - { label: 'Enabled', name: 'enabled', widget: 'boolean', default: true, required: false }
                - { label: 'Color', name: 'color', widget: 'color', allowInput: true, enableAlpha: true, default: '#000000', required: false }
        - { label: 'Body', name: 'body', widget: 'markdown' }
    - label: "About"
      name: "about"
      file: "content/about.md"
      fields:
        - label: 'Hero Banner'
          name: 'hero_banner'
          widget: 'object'
          fields:
            - { label: 'Image', name: 'image', widget: image, required: false }
            - label: 'text'
              name: 'text'
              widget: 'object'
              fields:
                - { label: 'Headline', name: 'headline', widget: 'text', required: false }
                - { label: 'Subtext', name: 'subtext', widget: 'text', required: false }
            - label: 'Background Size'
              name: 'background_size'
              widget: 'select'
              required: false
              options: 
                - { label: 'Cover', value: 'cover' }
                - { label: 'Contain', value: 'contain' }
            - label: 'Backdrop'
              name: 'backdrop'
              widget: 'object'
              fields:
                - { label: 'Enabled', name: 'enabled', widget: 'boolean', default: true, required: false }
                - { label: 'Color', name: 'color', widget: 'color', allowInput: true, enableAlpha: true, default: '#000000', required: false }
        - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Posts'
    name: 'posts'
    folder: 'content/posts/'
    extension: 'md'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD', dateFormat: 'YYYY-MM-DD', timeFormat: false }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
